### ISSUE TITLE
Syntax error in staging_windir.rb

### ISSUE THREAD

**Issue by bhundven** [voxpupuli/puppet-staging#102]
- [x] There is no existing issue or PR that addresses this problem

Optional, but makes our lives much easier:
- [x] The issue affects the latest release of this module at the time of
  submission
### Affected Puppet, Ruby, OS and module versions/distributions

Puppet: 3.8.4
Ruby: 1.8.7
OS: CentOS 6.7
Module: puppet-staging 2.0.0
### What are you seeing

Error loading fact /var/lib/puppet/lib/facter/staging_windir.rb: /var/lib/puppet/lib/facter/staging_windir.rb:2: syntax error, unexpected ':', expecting kEND
  confine osfamily: :windows
                   ^
### What behaviour did you expect instead

Not an error?
### How did this behaviour get triggered

We used to use nanliu-staging and changed to puppet-staging due to a module dependency
### Output log

sudo puppet agent -t --noop
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Loading facts
Error loading fact /var/lib/puppet/lib/facter/staging_windir.rb: /var/lib/puppet/lib/facter/staging_windir.rb:2: syntax error, unexpected ':', expecting kEND
  confine osfamily: :windows
                   ^
Info: Caching catalog for somehost
Info: Applying configuration version '1465851765'
Notice: Finished catalog run in 10.45 seconds
### Any additional information you'd like to impart

This change seems to be the issue: https://github.com/voxpupuli/puppet-staging/commit/d3c101614dcec2d0d09107b41089567557724a71

**Comment by electrical** [comment]
Hi,

I ran into the same issue. 1.7.0 was released to re-instate ruby 1.8.x support
Version 2.x has dropped that support.
In your case i would advise to pin to version 1.7.0

**Comment by prikkeldraad** [comment]
Too bad support on 1.8.x has been dropped. Lot's of modules depend on this staging. We are still on RHEL6 with no way to up Ruby. Well i'm pinning to older versions for now; missing out cool new features.

**Comment by bhundven** [comment]
pin ruby to 1.7.0? Before 2.0.0 of the puppet-staging module, there is 1.0.7, which still has this change, and 1.0.6, which also still has this change. 1.0.5 does not have a release on puppet forge.

**Comment by alexjfisher** [comment]
@bhundven `1.7.0` was a typo.  @electrical was actually thinking of `1.0.7`.  As far as I can see, this release *does* contain the fix you need in https://github.com/voxpupuli/puppet-staging/commit/6729b2a313e647af881d26f0e11b4f7fb7432b59

**Comment by stefanandres** [comment]
What is the plan here? I'm having the same issue on some CentOS-6.8 boxes.

**Comment by alexjfisher** [comment]
@stefanandres `1.0.7` is available if you need ruby 1.8 support.  IIRC it should have all the same features as the latest 2.x release.

**Comment by stefanandres** [comment]
Well, and then I will no longer get any updates for future changes. :/

Why is the confine :foo: bar syntax favored instead of confine :foo => :bar (which seems to work with both ruby versions)?

**Comment by alexjfisher** [comment]
@stefanandres I don't expect there will be much/any more development of this module, so in this case, you won't miss much.  New features are being added to the much improved puppet-archive module instead.

Voxpupuli have dropped ruby 1.8 support in all of their modules, but this isn't necessarily a problem for EL6 users. 
Have you started your migration to puppet 4 yet?  The puppet 4 AIO (all in one) packages come with their own ruby 2.1 and puppet 3 is EOL in 30 days time.
