### ISSUE TITLE
Add an opts parameter for tar

### ISSUE THREAD

**Issue by ardichoke** [voxpupuli/puppet-staging#142]
The staging module currently has an unzip_opts parameter which will get passed along to the unzip exec when run. This would be useful for tar (and probably other extraction methods as well). It would be especially useful in situations where developers ship configuration files in their archives which would then overwrite running configuration files.

**Comment by ekohl** [comment]
Sounds like a good idea. A PR would be very welcome.

**Comment by ardichoke** [comment]
Thanks for bumping this, I was neck deep in other work back in May, but find myself with some time to kill right now. PR submitted.
