### ISSUE TITLE
Deprecate this module in favour of puppet/archive

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/puppet-staging#162]
Hi everybody,

I would like to deprecate this module in favour of our archive module: https://github.com/voxpupuli/puppet-archive

Our archive module is well maintained and tested. Years ago it was created as the successor of staging, but staging was never deprecated. I do not see a value in a second module with a similar featureset. @voxpupuli/collaborators let me know what you think about it.

**Comment by jhoblitt** [comment]
Thre README already claims it is deprecated...

**Comment by bastelfreak** [comment]
at least the puppetlabs/mysql module still depends on it and we still do regular releases. Since it is already deprecated in the README.md it should not bother anyone when we also mark it as deprecated on the forge.

**Comment by tphoney** [comment]
Hi Everyone,

apologies for the the delay on getting back to this. I have created a PR
https://github.com/puppetlabs/puppetlabs-mysql/pull/1115 that will move the
mysql module from puppet-staging to puppet-archive. It works for me when
testing, but if others could give it a review, that would be brilliant. We
are using https://tickets.puppetlabs.com/browse/MODULES-6923 to track the
work. The plans is:

   1. Do a last release of mysql at the 6.x.x range.
   2. merge the staging -> archive PR
   3. Release a 7.0.0 of mysql.

If you have any questions, feel free to reach out.

TP

**Comment by bastelfreak** [comment]
I will prepare a final release. Afterwards we can discuss how we actually deprecate a module (which we never did in the past).
