### ISSUE TITLE
source_permissions in file.pp is raising a deprecation warning

### ISSUE THREAD

**Issue by cryssoft** [voxpupuli/puppet-staging#166]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:  2018.1.5
- Ruby:
- Distribution:
- Module version:

## How to reproduce (e.g Puppet code you use)
puppet agent -t

## What are you seeing
source_permissions in file.pp is raising a deprecation warning

## What behaviour did you expect instead
no deprecation warning

**Comment by ekohl** [comment]
Could you show the deprecation warning that is shown?

Other than that I'd urge you to migrate to https://github.com/voxpupuli/puppet-archive since this module is deprecated.

**Comment by Dan33l** [comment]
@ekohl i suppose it is related to this message : https://tickets.puppetlabs.com/browse/PUP-9332

The `README.md` show a deprecate message about the module. But, the module is not indicated as deprecated by forge and worst it is with flag `approved`.

**Comment by ekohl** [comment]
We discussed officially marking it deprecated. Until recently puppetlabs-mysql was still using it so we held off, but since 7.0.0 it doesn't anymore so we should revisit that decision.

**Comment by ekohl** [comment]
This module is deprecated in favor of [puppet-archive](https://github.com/voxpupuli/puppet-archive) and as such won't receive any more updates.
