### ISSUE TITLE
staging module can create 0 length files

### ISSUE THREAD

**Issue by vchepkov** [voxpupuli/puppet-staging#77]
Commands like wget can fail to download a file and create a file with 0 length instead
The next time agent runs it will see the file and won't retry to download it again.
I made an attempt to create a workaround in #42 , but it's not compatible with Windows

**Comment by ChrLau** [comment]
Is anybody working on this issue? I just have had the same problem due to a misconfiguration of our artifactory I got 0 byte tomcat-version.tar.gz files and apparently the puppetlabs-tomcat module uses staging to download and extract the .tar.gz.

**Comment by ekohl** [comment]
This module is deprecated in favor of [puppet-archive](https://github.com/voxpupuli/puppet-archive) and as such won't receive any more updates.
