### ISSUE TITLE
Release to puppet-community namespace on forge

### ISSUE THREAD

**Issue by mkrakowitzer** [voxpupuli/puppet-staging#84]
This module does not have a release on the forge. Can I go ahead and do this?

If we are happy to do this, @nanliu  could you deprecate nanliu/staging with a 999.999.999 release, and request the transfer the puppet approved status to puppet/staging ?

**Comment by nanliu** [comment]
Sure, same comment as archive.

**Comment by dhoppe** [comment]
What is the latest status on this issue? I have seen that this module is under current development, but modules like [puppetlabs-mysql](https://github.com/puppetlabs/puppetlabs-mysql) are using the old module as dependency. This could be a problem, if you are using tools like [librarian-puppet](https://github.com/rodjek/librarian-puppet) which automatically resolves dependencies.

**Comment by rnelson0** [comment]
This was finally completed in #93, yay!
