### ISSUE TITLE
Error loading staging_windir.rb

### ISSUE THREAD

**Issue by prasadjlv** [voxpupuli/puppet-staging#94]
I am a newbie here, so please bear with me. I am observing this error on a CentOS 6.7 with ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux], Puppet 3.8.3, and puppet-staging v1.0.6:

Error loading fact /etc/puppet/modules/staging/lib/facter/staging_windir.rb: /etc/puppet/modules/staging/lib/facter/staging_windir.rb:2: syntax error, unexpected ':', expecting kEND
  confine osfamily: :windows
                   ^

What am I doing wrong? Is the above being caused by the ruby version?

Thank you in advance for any pointers.

**Comment by petems** [comment]
Yep, this is a Ruby 1.8.7 issue. 

Is it possible to upgrade to Ruby 1.9.3 in your environment?

https://github.com/voxpupuli/plumbing/issues/36

**Comment by prasadjlv** [comment]
It's difficult to upgrade to Ruby 1.9.3 in our environments because of the tight version control, upstream yum repo and multiple systems involved. Is that my only option?

**Comment by petems** [comment]
You can switch back to using a version of the module before the 1.8.7 imcompatible changes, which I believe is `v1.0.5`

Can you try using that and see if it works fro you?

**Comment by prasadjlv** [comment]
I tried installing v1.0.5 and I'm got: 

No releases matching '1.0.5' are available from https://forgeapi.puppetlabs.com

**Comment by jyaworski** [comment]
@prasadjlv 1.0.5 might the in the 'nanliu' namespace. What I would do is to change the file locally to us the 1.8.7 hash syntax.

**Comment by prasadjlv** [comment]
@jyaworski thank you. Will do that.

**Comment by nomoresecrets** [comment]
@prasadjlv 

> What I would do is to change the file locally to use the 1.8.7 hash syntax.

How would I do this?
