### ISSUE TITLE
JSON syntax in staging_windir fact causes syntax error using Ruby 1.8

### ISSUE THREAD

**Issue by smoeding** [voxpupuli/puppet-staging#96]
I'm using Puppet 3.8.7 on Debian 4 & 5 machines (don't ask...). Puppet uses Ruby 1.8.7 on these machines which causes a syntax error with this module:

```
Error loading fact /var/lib/puppet/lib/facter/staging_windir.rb: /var/lib/puppet/lib/facter/staging_windir.rb:2: syntax error, unexpected ':', expecting kEND
  confine osfamily: :windows
                   ^
```

Could the JSON-style syntax be replaced with the _old_ hash rocket syntax to make this module work on older environments again?

**Comment by jyaworski** [comment]
@smoeding the newest version of archive has dropped support for ruby 1.8.

**Comment by juniorsysadmin** [comment]
@smoeding You're going to need to downgrade to 1.05. Voxpupuli policy is not to explicitly support Ruby 1.8.7. Sadly the Changelogs for this module could have been a bit better. We're working on making this policy a bit more visible: https://github.com/voxpupuli/plumbing/issues/36
